export const SEARCH_MOVIE_START = "SEARCH_MOVIE_START";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";
export const SEARCH_MOVIE_COMPLETE = "SEARCH_MOVIE_COMPLETE";
export const CLEAR_MOVIE_LIST = "CLEAR_MOVIE_LIST";

export const SEARCH_MOVIE_BY_ID_START = "SEARCH_MOVIE_BY_ID_START";
export const SEARCH_MOVIE_BY_ID_ERROR = "SEARCH_MOVIE_BY_ID_START_ERROR";
export const SEARCH_MOVIE_BY_ID_COMPLETE = "SEARCH_MOVIE_BY_ID_START_COMPLETE";

export const ADD_FAV_LIST_START = "ADD_FAV_LIST_START";
export const ADD_FAV_LIST_ERROR = "ADD_FAV_LIST_ERROR";
export const ADD_FAV_LIST__COMPLETE = "ADD_FAV_LIST__COMPLETE";
